on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

        # プロジェクトで必要な依存関係をインストールするステップ
      - name: Install dependencies
        run: npm install # package.jsonとpackage-lock.jsonに基づいて、再現性のあるクリーンインストールを実行

      - name: Build
        run: npm run build

      - name: Run Biome (fix & check)
        run: |
          npm run biome fix
          npm run biome check

      - name: Run Lint
        run: npm run lint

      - name: Run Test
        run: npm run test
